kind: PersistentVolumeClaim
apiVersion: v1

metadata:
  name: fleetman-logging-pvc
  namespace: kube-system  

spec:
  storageClassName: fleetman-primary-storage
  
  accessModes:
  - ReadWriteOnce
  
  resources:
    requests:
      storage: 31Gi
